Namespace: &namespace default

replicaSet: rs0
replicas: 3
port: 27017

auth:
  enabled: false
  # adminUser:
  # adminPassword:
  # key:
  # existingKeySecret:
  # existingAdminSecret:

# Specs for the Docker image for the init container that establishes the replica set
installImage:
  name: gcr.io/google_containers/mongodb-install
  tag: 0.4
  pullPolicy: Always

# Specs for the MongoDB image
image:
  name: mongo
  tag: 3.4
  pullPolicy: Always

# Annotations to be added to MongoDB pods
podAnnotations: {}

resources: {}
# limits:
#   cpu: 100m
#   memory: 512Mi
# requests:
#   cpu: 100m
#   memory: 512Mi

Scheduling:
  Affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: role
            operator: In
            values:
            - mongodb
          - key: namespace
            operator: In
            values:
            - *namespace
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: chart
            operator: In
            values:
            - mongodb-replicaset
        topologyKey: 'kubernetes.io/hostname'


Persistence:
  Enabled: false

  StorageClass: standard
  AccessMode: ReadWriteOnce
  Size: 10Gi

  Annotations: {}

Backup:
  Enabled: true

  Image:
    Name: "quay.io/smarsh/mongodump"
    Tag: "s3"

  Resources: {}

  Persistence:
    Enabled: false

    StorageClass: standard
    AccessMode: ReadWriteOnce
    Size: 10Gi

    Annotations: {}

  S3_Bucket: "development.smarsh.com"

# Annotations to be added to the service
serviceAnnotations: {}

# Entries for the MongoDB config file
configmap:
  storage:
    dbPath: /data/db
  net:
    port: 27017
  replication:
    replSetName: rs0
# security:
#   authorization: enabled
#   keyFile: /keydir/key.txt
InitScripts:
- |
  #!/bin/bash
  #
  # https://docs.mongodb.com/manual/reference/ulimit/
  echo "Running optimizations"

Monitoring:
  Enabled: false

  Image:
    Name: 'quay.io/smarsh/mongodb_exporter'
    Tag: 'latest'

  Port:
    Container: 9104
