{{- if .Values.Backup.Enabled -}}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ template "fullname" . }}-backup
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
  name: {{ template "fullname" . }}-backup
  namespace: {{ .Values.Namespace | default "default" }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: {{ template "fullname" . }}-backup
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
    spec:
      containers:
      - name: "mongodump"
        image: "{{ .Values.Backup.Image.Name }}:{{ .Values.Backup.Image.Tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
        resources:
{{ toYaml .Values.Backup.Resources | indent 10 }}
        env:
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "POD_IP"
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: "MONGO_URI"
          value: 'mongodb://{{ template "fullname" .}}-0.{{ template "fullname" .}}:27017'
        - name: "S3_BUCKET"
          value: "{{ .Values.Backup.S3_Bucket }}"
        - name: "S3_PATH"
          value: "{{ .Release.Name }}"
      {{- if .Values.Backup.Image.PullSecret }}
      imagePullSecrets:
      - name: {{ .Values.Backup.Image.PullSecret }}
      {{- end }}
      {{- if .Values.Backup.NodeSelector }}
      nodeSelector:
{{ toYaml .Values.Backup.NodeSelector | indent 8 }}  
      {{- end }}
{{- end }}
