{{- if and (.Values.auth.enabled) (not .Values.auth.existingAdminSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "adminSecret" . }}
  namespace: {{ .Values.Namespace | default .Release.Namespace }}
type: Opaque
data:
  user: {{ .Values.auth.adminUser | b64enc }}
  password: {{ .Values.auth.adminPassword | b64enc }}
{{- end -}}
