apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    chart: {{ .Chart.Name | quote }}
    component: {{ template "fullname" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "shortname" . }}
  namespace: {{ .Values.Namespace | default .Release.Namespace }}
data:
  mongod.conf: |
{{ toYaml .Values.configmap | indent 4 }}
{{- range $key, $val := .Values.InitScripts }}
  init{{ $key }}.sh: |-
{{ $val | indent 4 }}
{{- end }}
