{{- if and (.Values.auth.enabled) (not .Values.auth.existingKeySecret) -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    chart: {{ .Chart.Name }}
    component: {{ template "fullname" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "keySecret" . }}
  namespace: {{ .Values.Namespace | default .Release.Namespace }}
type: Opaque
data:
  key.txt: {{ .Values.auth.key | b64enc }}
{{- end -}}

