apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "shortname" . }}
  namespace: {{ .Values.Namespace | default "default" }}
data:
  mongod.conf: |
{{ toYaml .Values.configmap | indent 4 }}
{{- range $key, $val := .Values.InitScripts }}
  init{{ $key }}.sh: |-
{{ $val | indent 4 }}
{{- end }}
